name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and tag the Docker image
      run: |
        docker build . --file Dockerfile --tag 7eventy7/discodrome:$(echo ${{ github.sha }} | cut -c1-7) --tag 7eventy7/discodrome:latest
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
        
    - name: Push to DockerHub
      run: |
        docker push 7eventy7/discodrome:$(echo ${{ github.sha }} | cut -c1-7)
        docker push 7eventy7/discodrome:latest